# Build inside the target-platform container so Buildx can produce both amd64 and arm64 images.
FROM rust:1-bookworm AS builder

RUN apt-get update \
  && apt-get install -y --no-install-recommends libssl-dev pkg-config \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /build
COPY vibi-dpu/Cargo.toml vibi-dpu/Cargo.lock ./
COPY vibi-dpu/src ./src
RUN cargo build --release --locked

# Keep the existing Ubuntu runtime and its required command-line tools/libraries.
FROM ubuntu:24.04

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates git ripgrep libssl3 \
  && rm -rf /var/lib/apt/lists/*

ARG GCP_CREDENTIALS
ARG TOPIC_NAME
ARG SUBSCRIPTION_NAME
ARG DPU_QUEUE_TRANSPORT
ARG DPU_POLL_INTERVAL_MS
ARG DPU_JOB_LEASE_SECONDS
ARG BITBUCKET_CLIENT_ID
ARG BITBUCKET_CLIENT_SECRET
ARG BITBUCKET_BASE_URL
ARG INSTALL_ID
ARG SERVER_URL
ARG GITHUB_APP_ID
ARG GITHUB_APP_CLIENT_ID
ARG GITHUB_APP_CLIENT_SECRET
ARG GITHUB_BASE_URL
ARG GITHUB_PAT
ARG PROVIDER

ENV GCP_CREDENTIALS=$GCP_CREDENTIALS
ENV TOPIC_NAME=$TOPIC_NAME
ENV SUBSCRIPTION_NAME=$SUBSCRIPTION_NAME
ENV DPU_QUEUE_TRANSPORT=$DPU_QUEUE_TRANSPORT
ENV DPU_POLL_INTERVAL_MS=$DPU_POLL_INTERVAL_MS
ENV DPU_JOB_LEASE_SECONDS=$DPU_JOB_LEASE_SECONDS
ENV BITBUCKET_CLIENT_ID=$BITBUCKET_CLIENT_ID
ENV BITBUCKET_CLIENT_SECRET=$BITBUCKET_CLIENT_SECRET
ENV BITBUCKET_BASE_URL=$BITBUCKET_BASE_URL
ENV INSTALL_ID=$INSTALL_ID
ENV SERVER_URL=$SERVER_URL
ENV GITHUB_APP_ID=$GITHUB_APP_ID
ENV GITHUB_APP_CLIENT_ID=$GITHUB_APP_CLIENT_ID
ENV GITHUB_APP_CLIENT_SECRET=$GITHUB_APP_CLIENT_SECRET
ENV GITHUB_BASE_URL=$GITHUB_BASE_URL
ENV GITHUB_PAT=$GITHUB_PAT
ENV PROVIDER=$PROVIDER

WORKDIR /app
COPY --from=builder /build/target/release/vibi-dpu /app/vibi-dpu
COPY prompts /app/prompts
RUN mkdir /app/config

CMD ["/app/vibi-dpu"]
