# Use a lightweight Linux distribution as the base image
FROM ubuntu:latest

# # Install dependencies required by the application
RUN \
  apt-get update && \
  apt-get install -y ca-certificates git ripgrep libssl1.1 && \
  apt-get clean

ARG GCP_CREDENTIALS
ARG TOPIC_NAME 
ARG SUBSCRIPTION_NAME
ARG BITBUCKET_CLIENT_ID
ARG BITBUCKET_CLIENT_SECRET
ARG BITBUCKET_BASE_URL
ARG INSTALL_ID
ARG SERVER_URL
ARG GITHUB_APP_ID
ARG GITHUB_APP_CLIENT_ID
ARG GITHUB_APP_CLIENT_SECRET
ARG GITHUB_BASE_URL
ARG GITHUB_PAT
ARG PROVIDER


ENV GCP_CREDENTIALS=$GCP_CREDENTIALS  
ENV TOPIC_NAME=$TOPIC_NAME
ENV SUBSCRIPTION_NAME=$SUBSCRIPTION_NAME
ENV BITBUCKET_CLIENT_ID=$BITBUCKET_CLIENT_ID
ENV BITBUCKET_CLIENT_SECRET=$BITBUCKET_CLIENT_SECRET
ENV BITBUCKET_BASE_URL=$BITBUCKET_BASE_URL
ENV INSTALL_ID=$INSTALL_ID
ENV SERVER_URL=$SERVER_URL
ENV GITHUB_APP_ID=$GITHUB_APP_ID
ENV GITHUB_APP_CLIENT_ID=$GITHUB_APP_CLIENT_ID
ENV GITHUB_APP_CLIENT_SECRET=$GITHUB_APP_CLIENT_SECRET
ENV GITHUB_BASE_URL=$GITHUB_BASE_URL
ENV GITHUB_PAT=$GITHUB_PAT
ENV PROVIDER=$PROVIDER

COPY ./vibi-dpu/target/debug/vibi-dpu /app/vibi-dpu
COPY ./pubsub-sa.json /app/pubsub-sa.json
COPY ./repo-profiler.pem /app/repo-profiler.pem
COPY ./prompts /app/prompts

# Create directory for configuration
RUN mkdir /app/config

# Start the Rust application
CMD ["/app/vibi-dpu"]
